#include <stdio.h>
int main()
{
    int note500,note100,note50,note20,note10,note5,note2,note1,amount;
    scanf("%d",&amount);
    if(note500=amount/500)
    {
        printf("500:%d\n",note500);
    }
    else
    {
        printf("500:0\n");
    }
    amount%=500;
    if(note100=amount/100)
    {
        printf("100:%d\n",note100);
    }
    else
    {
        printf("100:0\n");
    }
    amount%=100;
    if(note50=amount/50)
    {
        printf("50:%d\n",note50);
    }
    else
    {
        printf("50:0\n");
    }
    amount%=50;
    if(note20=amount/20)
    {
        printf("20:%d\n",note20);
    }
    else
    {
        printf("20:0\n");
    }
    amount%=20;
    if(note10=amount/10)
    {
        printf("10:%d\n",note10);
    }
    else
    {
        printf("10:0\n");
    }
   amount%=10;
   if(note5=amount/5)
   {
       printf("5:%d\n",note5);
   }
   else
   {
       printf("5:0\n");
   }
   amount%=5;
   if(note2=amount/2)
   {printf("2:%d\n",note2);}
   else
   {
       printf("2:0\n");
   }
   amount%=2;
   if(note1=amount/1)
   {
       printf("1:%d\n",note1);
   }
   else
   {  printf("1:0\n");
   }
	return 0;
}